### ISSUE TITLE
Wrong username when commenting on scores

### ISSUE THREAD

**Issue by David-Dressler** [COLARDYNIT/hwbot-issues#11]
When commenting directly on a score, a different username appears then the one of the commenters account. In the forum it is matched to the correct account. This only appears to apply to some accounts.
Example: 
https://hwbot.org/submission/4060158_tantekaethe_superpi___32m_core_i5_760_7min_21sec_188ms
https://community.hwbot.org/topic/187706-tantekaethe-core-i5-760-49997mhz-7min-21sec-188ms-superpi-32m/

**Comment by frederikcolardyn** [comment]
Known bug of forum migration. No proper approach to fix found yet...

**Comment by ddevrien** [comment]
Managed to correct most of them with a script.
The script checked for duplicate links and removed links that did not have a exact username / forum user name match. Let me know if you find more examples @David-Dressler!
