### ISSUE TITLE
PCMARK VANTAGE  Hall of Fame top 20 scores can't be submitted

### ISSUE THREAD

**Issue by ksateaaa23** [COLARDYNIT/hwbot-issues#12]
pcmark vantage Hall of Fame top 20 score can't be submitted. it says valid link is not available. doesn't work with or without http etc. not working for few months now. 
to make it more clear 20th rank score is 38818, so any score less than or equal to 38818 can be submitted but not better than that.

https://community.hwbot.org/topic/187099-pcmark-vantage-top-20-global-score-cant-be-submitted/

**Comment by frederikcolardyn** [comment]
Pattern updated to (http|https)://www.3dmark.com/pcmv/[0-9]*
