### ISSUE TITLE
Users duplicated in the Country rankings

### ISSUE THREAD

**Issue by ghost** [COLARDYNIT/hwbot-issues#16]
When I click on any country (for example [Australia](https://hwbot.org/country/australia/)), the page lists overclockers from that country broken down by league:

![image](https://user-images.githubusercontent.com/47166173/52317385-af669380-29b7-11e9-9ea1-f00ffe7eba16.png)

However when I now click "view full ranking", it sends me to a [permalink](https://hwbot.org/search/members/permalink?countryId=14&league=extreme&orderBy=rank) which lists every overclocker at least twice in an unordered way:
![image](https://user-images.githubusercontent.com/47166173/52317452-f3f22f00-29b7-11e9-8321-cb5a8250dc69.png)

I'm not sure whether this is due to the upcoming Leagues rework, but I thought I would mention it anyway :)

**Comment by frederikcolardyn** [comment]
Fix in progress

**Comment by frederikcolardyn** [comment]
The fix shows all members without duplicates, but it's not an optimal view at all. This is the best that I can do, if not ok i better remove it.
