### ISSUE TITLE
Chipset ranking doesnt show all records

### ISSUE THREAD

**Issue by random2324** [COLARDYNIT/hwbot-issues#17]
Ranking just shows 9 results while it should be 20 (Yes there were actually more than 20 results made with that chipset) ;)
![ranking](https://user-images.githubusercontent.com/19872920/52371134-fd7da480-2a54-11e9-9d65-a3fc29cf83c1.jpg)

**Comment by frederikcolardyn** [comment]
Troubleshooting, the queries to make these rankings are complex.

**Comment by frederikcolardyn** [comment]
Fixed, going to production in next build.
