### ISSUE TITLE
Submission Search doesnt show correct results

### ISSUE THREAD

**Issue by random2324** [COLARDYNIT/hwbot-issues#18]
So lets search subs of user "greg". Greg has zero results, so the search should actually return zero results. Instead it shows results from another user.

This example might make not many sense as "greg" is a no active user. But believe me, things drove me mad when I was looking for results from a specific user but just couldnt find his results via the search.
![sub_search1](https://user-images.githubusercontent.com/19872920/52375710-98c84700-2a60-11e9-97e9-aee7d21752f3.jpg)
![sub_search2](https://user-images.githubusercontent.com/19872920/52375713-99f97400-2a60-11e9-834f-a4e180157704.jpg)

**Comment by frederikcolardyn** [comment]
Search submissions uses wildcards by defaults (partial match is ok), otherwise only exact matches would return results. Which is likely not wanted.

Your use care would be covered by looking up greg, and then choose submissions > all.
https://hwbot.org/user/greg/#My_Submissions
