### ISSUE TITLE
HWBOT Admin - Possibility to sort search results

### ISSUE THREAD

**Issue by random2324** [COLARDYNIT/hwbot-issues#19]
Either from A-Z or upwards / downwards.
![deepinbildschirmfoto_20190206224351](https://user-images.githubusercontent.com/19872920/52376338-2a848400-2a62-11e9-9d0b-5d851c101904.png)

And yes, page 1 of the search results is still unreachable.

**Comment by ddevrien** [comment]
implemented + improvements to the pagination
