### ISSUE TITLE
submit error on both oc-esport and hwbot.org

### ISSUE THREAD

**Issue by matsglobetrotter1** [COLARDYNIT/hwbot-issues#22]
Since 24 hours atleast  i cant submit properly. When having filled all the data  in a sub on hwbot.org and hit the submit benchmark button the system seemingly uploads the data and accept the sub. however the system do not exit the submission and keep saying submitting indefinitely. If I hit the submit button again it will again upload but not exit the screen and hang again. I have tried it in google chrome on win7 and win 10 as well as on firefox on win 7.
Meanwehile if i open a new browserwindow and go to hwbot.org and my profile page i can see the submission as completed. since i want to take part in the competition on oc-esports i then have to open my submissions find the sub and click participate.

Meanwhile on the same browsers and win 7 and win 10 the OC-esports simply go in a loop trying to load the  open for submission page but never shows the form (I am logged in)

**Comment by ddevrien** [comment]
hey @matsglobetrotter1 , apologies for late response. Do you have any recent examples of this issue or can I close it?

**Comment by matsglobetrotter1** [comment]
Hi, no worries on late reply i know u guys are busy. Infact i have not notice this problem for the last month not for normal submissions nor the competition ones this seems to be resolved thanks for keeping hwbot going:-)

**Comment by ddevrien** [comment]
Alright, closing ticket then.
