### ISSUE TITLE
link to OC-esport from hwbot.org

### ISSUE THREAD

**Issue by matsglobetrotter1** [COLARDYNIT/hwbot-issues#24]
Hi Considering the amount of time we need to move between the OC-esport site and HWbot. org. please add a link among the top menu to the OC-esport site. Since the links for competition only refer directly to the Hwbot presentations it makes sense for users.
The reciprocal link back to HWbot.org already exist on OC-esports

**Comment by frederikcolardyn** [comment]
Ok, a link to oc-esports page will be on top right in next update.

**Comment by frederikcolardyn** [comment]
fixed in next release

**Comment by matsglobetrotter1** [comment]
Great:-) thanks
