### ISSUE TITLE
Checking submissions via a user's Hardware Library always returns 0 results

### ISSUE THREAD

**Issue by ghost** [COLARDYNIT/hwbot-issues#30]
A useful way to find certain submissions is another user's Hardware Library, e.g. [https://hwbot.org/user/bilko/#Hardware_Library](https://hwbot.org/user/bilko/#Hardware_Library):

![image](https://user-images.githubusercontent.com/47166173/57991651-4e675500-7aa8-11e9-936c-54b8bfcb9eee.png)

Here owned hardware is listed along with the number of associated submissions. In the past, clicking on the number returned a list of those submission but now that query always returns a blank list, no matter how many submissions actually exist for those criteria:

![image](https://user-images.githubusercontent.com/47166173/57991704-82db1100-7aa8-11e9-9520-b00571ebcb57.png)

![image](https://user-images.githubusercontent.com/47166173/57991713-8d95a600-7aa8-11e9-8d6a-11aac665f0b1.png)

**Comment by frederikcolardyn** [comment]
My profile works fine, seems to be specific to Bilko. Checking!

**Comment by frederikcolardyn** [comment]
fixed in next release
