### ISSUE TITLE
GPUPI 3.2/3.3> 4 cards submissions in 4 cards submission Global rankings (scores) - they're cheating on purpose.

### ISSUE THREAD

**Issue by PiotrOrkisz** [COLARDYNIT/hwbot-issues#31]
Hello,

There are many submissions which doesn't follow the rules of 4 cards in GPUPI 3.2 and 3.3 submissions. Those should be deleted but apparently they're not although I have been reporting those many times. 
https://hwbot.org/submission/3991289_x_computers.eu_gpupi___1b_4_geforce_rtx_2080_ti_0sec_639ms - 10 cards
https://hwbot.org/submission/4159680_macdaffy_gpupi___1b_4_geforce_gtx_1080_ti_0sec_859ms - 16 cards
https://hwbot.org/submission/3785732_pijonson_gpupi___1b_4_geforce_gtx_1080_ti_1sec_466ms - 8 cards
https://hwbot.org/submission/3579742_dhenzjhen_gpupi___1b_4_tesla_m40_1sec_458ms - 10 cards
32B
https://hwbot.org/submission/4159675_macdaffy_gpupi___32b_4_geforce_gtx_1080_ti_52sec_442ms -16 cards
https://hwbot.org/submission/3579743_dhenzjhen_gpupi___32b_4_tesla_m40_1min_45sec_177ms -10 cards
https://hwbot.org/submission/3784305_victorshavkin_gpupi___32b_4_geforce_gtx_1080_ti_1min_59sec_267ms - 7 cards
https://hwbot.org/submission/3050127_oldcomer_gpupi___32b_4_radeon_r9_290x_2min_22sec_104ms - 8 cards

3.3 1B
https://hwbot.org/submission/4143713_pijonson_gpupi_v3.3___1b_4_geforce_rtx_2080_ti_0sec_549ms - 8 cards

3.3 32B
https://hwbot.org/submission/4151457_bilko_gpupi_v3.3___32b_4_radeon_r9_290x_2min_59sec_915ms - 5 cards

Those guys knows exactly what they're are doing and they're not even that decent to disable points for those submissions! 

That kills OC spirit right away. Those 16 cards are even downclocked IMHO - just to run. 

Please delete them as they should be deleted long time ago - not applying to rules. 

Cheaters in sports gets banned. Even in eSports. In OC sports it's fair to cheat and get a fame with points.

Peter

ADVenturePO

**Comment by jfoster** [comment]
This issue tracker really isn't the correct place to report submissions. I had a quick glance at a few of the linked submissions and as far as I can tell all of them are submitted correctly and completely valid.
Just a bug on hwbot's end with >4 cards appearing by mistake on the 4 card global ranking, next time report the issue/bug without bringing in your emotions or pointing fingers, report subs that actually break the rules in the appropriate place and real, actual cheaters will get dealt with.

**Comment by PiotrOrkisz** [comment]
Dear jfoster. 

As I understand - not to worry, I just won't get points for my World Record breaking submissions -  and people who submitted over 4 cards results and see they get WR points in 4 cards category are totally OK? :) That's a right thing to do. 
HWBOT Issue tracker is not the right place to report issues with wrong amount of cards in strict amount of cards category submission? 
I'll break it down for You:
HWBOT (  understood as ICT system of collecting data from user submissions) is wrongly qualifying over 4 cards submissions to 4 cards only category of Word Records ( that's an issue).

**Every overclocker that submitted in those categories is given almost no point score due to the gap between wrongful record (with higher amount of cards) and his right one.**
 
I don't know if you're an overclocker. And I don't know if you had ever tried to beat a World Record but believe me it takes a lot of effort.
So your opinion, and dislike of  mypointing fingers with emotions after reporting to HWBOT a lot of time this inappropriate scores a right reaction. Nice and polite. Showing that you care. That you'll take some actions.

Sorry that I bothered HWBOT-issues with HWBOT issue. 

Exactly which place do You mean when You state "the appropriate place"?
Reporting it at submission directly didn't bring anything.
Reporting it on forums didn't either.
Reporting it here brought me just an info that everything with those submissions is ok.
Those submission are just messing up GPUPI records totally. No problem. 

Whole month passed. Nothing happened.  Nothing changed.
If using a tank in a destruction derby challenge is ok for you than OK. I may understand why don't you see it as a violation of rules.

**Comment by PiotrOrkisz** [comment]
Also: this place is marked HWBOT-issues not HWBOT-cheatersreporting. 
"report subs that actually break the rules in the appropriate place and real, actual cheaters will get dealt with." 
Maybe you should consider to change it than?
Or my translator is bad:  it doesn't in any place say that an issue is translatable to cheating.

**Comment by frederikcolardyn** [comment]
Hi PiotrOrkisz,

Mods don't use the bug tracker. Please use the forums or report functionality on hwbot.org for this.

**Comment by PiotrOrkisz** [comment]
Hello Frederik,

which section of hwbot.org should i use? Reporting or forums?
--------------------------------
Regards

*Piotr Orkisz*

*+48 731 064 164 *

ADVenture.PiotrOrkisz@gmail.com <adventure.piotrorkisz@gmail.com>

[image: Facebook] <https://www.facebook.com/ADVenturePO>

Jestem uczestnikiem programu weryfikacji kontrahentów:
*RZETELNA* *Firma *
Możesz mnie sprawdzić na https://www.rzetelnafirma.pl/0B7JYKZT



śr., 29 maj 2019 o 12:23 Frederik Colardyn <notifications@github.com>
napisał(a):
