### ISSUE TITLE
Second donation to hwbot but still no achievement in user profile

### ISSUE THREAD

**Issue by marcobelmonte** [COLARDYNIT/hwbot-issues#32]
![image](https://user-images.githubusercontent.com/4238826/58755349-2956e700-8497-11e9-8b12-a5de8f4179a4.png)

Checking user profile achievements:

![image](https://user-images.githubusercontent.com/4238826/58755352-425f9800-8497-11e9-80a4-01acb3b0942c.png)

Maybe this isn't an automatic thing? If it isn't let me know where to report it on the forums or where I can find further instructions.

**Comment by ghost** [comment]
As a workaround, have you tried clicking the achievement, clicking "recalculate" and then navigating back to the the achievements tab on your profile page?

**Comment by marcobelmonte** [comment]
No, but let me try that right now - maybe it is that easy??!?

**Comment by marcobelmonte** [comment]
I don't think that button is working either. I can click on it but the response just "flashes" so quickly it is obvious there is no connection attempt to the server and a quick look at the script seems to suggest it's not enabled but I could be wrong:

![image](https://user-images.githubusercontent.com/4238826/59576439-a0ce6e00-9074-11e9-973c-7e608f8898e5.png)

**Comment by frederikcolardyn** [comment]
If i remember correctly donations achievement is something that massman awarded manually. Dennis can you check?

**Comment by ddevrien** [comment]
@marcobelmonte could you let me know your HWBOT username? I'll award the achievement then.

**Comment by ddevrien** [comment]
Donation awarded to user marco.is.not.80.

**Comment by marcobelmonte** [comment]
Thanks guys!
