### ISSUE TITLE
"Rankings" button returns empty list for GPUs

### ISSUE THREAD

**Issue by ghost** [COLARDYNIT/hwbot-issues#34]
Hi,

This only happens under certain conditions but if I check a CPU (e.g. the [9700K](https://hwbot.org/hardware/processor/core_i7_9700k/)) and then click any of the **GPU** benches under the "Core i7 9700K used in other benchmarks" section at the bottom (e.g. [Fire Strike](https://hwbot.org/benchmark/3dmark_-_fire_strike/rankings?hardwareTypeId=processor_5774&cores=8#start=0#interval=20)) it defaults to a weird number of GPUs like 8 and the result is always blank, as there is no such thing as 8-way Fire Strike:

![image](https://user-images.githubusercontent.com/47166173/59811813-70503380-9303-11e9-95ad-7541f9fa3a23.png)

This is a problem because: 

- it is not obvious at all what is happening here because the link could just as easily be blank because there are no submissions
- even those people who know the "trick" to get the correct list (click on "Number of cores: 1x") get annoyed because every time you click such a link you first have to apply the trick to get the correct list

**Comment by ddevrien** [comment]
it just takes the same number of cores as the cpu has (so 8x in this case). But you're totally right it doesn't make any sense.

**Comment by ddevrien** [comment]
Fixed now, by default it will show results with any number of cores if the selected hardware has a different type than the application ranking type (so select CPU and show aquamark for example).
