### ISSUE TITLE
hwbot player tags aren't working properly anymore.

### ISSUE THREAD

**Issue by marcobelmonte** [COLARDYNIT/hwbot-issues#4]
I think this will need to be updated to reflect the new rules and season (which I love by the way - in fact - love all the new stuff great job!):

![image](https://user-images.githubusercontent.com/4238826/51970787-9cd6e200-242c-11e9-9127-1624ce86fb98.png)

**Comment by frederikcolardyn** [comment]
Thanks for the report! I'll check what goes wrong.

**Comment by frederikcolardyn** [comment]
I see the current logic shows season points, but it makes more sense to show career points instead to be backwards compatible.

**Comment by frederikcolardyn** [comment]
FIx is in production, next time a player tag is generated it will contain career instead of seasonal points.
