### ISSUE TITLE
World record page frequently does not load

### ISSUE THREAD

**Issue by ghost** [COLARDYNIT/hwbot-issues#6]
This page: https://hwbot.org/benchmarks/world_records

... often doesn't load fully, just showing headings like this:

![image](https://user-images.githubusercontent.com/47166173/52023353-ad528f80-24f4-11e9-9406-9267352f0b77.png)

It seems like the results get pulled from the live DB every time, would it make more sense to cache the page and only update the records for example once per day? I think this is a page a lot of first-time visitors go to and it also doesn't change very frequently so it would be more important for it to render correctly than be 100% up-to-date.

**Comment by frederikcolardyn** [comment]
Found the issue, it had to do with forcing HTTPS.
