### ISSUE TITLE
New mobile tab does not update.

### ISSUE THREAD

**Issue by krusic22** [COLARDYNIT/hwbot-issues#8]
The new mobile submission tab has not been updated since forever.

![image](https://user-images.githubusercontent.com/8352435/52092041-b441d680-25b6-11e9-8a63-c1a637d70dd7.png)

**Comment by frederikcolardyn** [comment]
Hmm, seems like a caching issue on your browser. Mine shows a list of today's submissions. I'll check the cache headers.

**Comment by krusic22** [comment]
Looks like someone fixed it.
Since it also updated for me now.
